# Tomcat
server:
  port: 8080

spring:
  # 环境 dev|test|pro
  profiles:
    active: test
  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    host: localhost
    port: 6379
    password:       # 密码（默认为空）
  servlet:
    multipart:
      maxFileSize: 104857600 #100MB
      maxRequestSize: 104857600 #100MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher  #解决swaggerUI不匹配接口
  main:
    allow-bean-definition-overriding: true #允许bean定义覆盖springboot2.1.x及以上版本默认禁止
    allow-circular-references: true #允许循环依赖引用springboot2.6.x及以上版本默认禁止

swagger:
  enable: true
  title: X-SpringBoot API
  description: API 描述
  version: 5.0.0
  author: czx
  url: https://github.com/yzcheng90/X-SpringBoot
  email: object_czx@163.com

# autofull 配置
autofull:
  showLog: false
  maxLevel: 1
  currLevel: 0
  encryptFlag: "@autofull@"
  encryptKeys: "abcdefg123456789"

#七牛 AK  和  SK可以去密钥管理中查询
qiniu:
  accessKey: 2222
  secretKey: 33333
  bucketName: qh-file
  domain: https://www.qiniu.com
  prefix: task

# mybaits-plus配置
mybatis-plus:
  # MyBatis Mapper所对应的XML文件位置
  mapper-locations: classpath:/mapper/**/*Mapper.xml
  global-config:
    # 关闭MP3.0自带的banner
    banner: false
    db-config:
      # 主键类型 0:数据库ID自增 1.未定义 2.用户输入 3 id_worker 4.uuid 5.id_worker字符串表示
      id-type: 0
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: 1
      # 默认数据库表下划线命名
      table-underline: true

# Sa-Token配置
sa-token:
    # token名称 (Same-Site=Strict)
    token-name: token
    # token有效期，单位s 默认30天, -1代表永不过期
    timeout: 2592000
    # token临时有效期 (指定时间内无操作就视为token过期) 单位s 默认-1永不过期
    activity-timeout: -1
    # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
    is-concurrent: true
    # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
    is-share: false
    # token风格
    token-style: uuid
    # 是否输出操作日志
    is-log: true

